# Generated by Django 5.0.6 on 2024-06-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='employees',
            field=models.ManyToManyField(through='hotelApp.RoomEmployee', to='hotelApp.employee'),
        ),
        migrations.RemoveField(
            model_name='roomemployee',
            name='employees',
        ),
        migrations.AddField(
            model_name='roomemployee',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.employee'),
        ),
    ]
