# Generated by Django 5.0.6 on 2024-06-05 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('typeballoon', models.CharField(max_length=15)),
                ('estYear', models.IntegerField()),
                ('out_of_Europe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeballoon', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('yearofbirth', models.IntegerField()),
                ('hoursflying', models.IntegerField()),
                ('title', models.CharField(max_length=15)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloonApp.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('airportBegin', models.CharField(max_length=15)),
                ('airportEnd', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='cover_images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloonApp.airline')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloonApp.balloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloonApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PilotsAirline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloonApp.airline')),
                ('pilots', models.ManyToManyField(to='balloonApp.pilot')),
            ],
        ),
    ]
