# Generated by Django 5.0.6 on 2024-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='supplements/')),
                ('code', models.CharField(max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('pro', 'Proteins'), ('vit', 'vitamins'), ('cre', 'creatines'), ('amino', 'amino acids'), ('pre', 'pre-workout')], max_length=6)),
                ('description', models.TextField()),
            ],
        ),
    ]
